### ISSUE TITLE
Black and white logo

### ISSUE THREAD

**Issue by Finii** [vlang/v-logo#5]
At www.nerdfonts.com we embed a lot of icons into fonts.

A lot of programming languages have their icons there, to show a meaningful icon for filesystem viewers, for example.

The addition of `V` has been requested, and I took this color logo and transmogrified it into a bw font (i.e. recognizable in small sizes) one. The relevant PR is here: https://github.com/ryanoasis/nerd-fonts/pull/1048

This is how it looks like:

![image](https://user-images.githubusercontent.com/16012374/212365704-65efa675-3c2c-4743-b245-7fab44e07e73.png)

Please let me know if you have objections. If I hear nothing this will be pulled into Nerd Fonts.

**Comment by medvednikov** [comment]
Hi @Finii 

Looks good to me!

**Comment by Finii** [comment]
Great, thanks for the feedback!

To be honest I already put it into Nerd Fonts v2.3.3 and released it, two weeks ago :slightly_smiling_face: 

Feel free to add it to this repo if you like.
https://github.com/ryanoasis/nerd-fonts/blob/master/src/svgs/vlang_nf.svg
Although I edited it with `inkscape` and thus have no `.gvdesign` files.
